### ISSUE TITLE
tabulate breaks on large tables

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-metadata#15]
It looks like very very large tables can cause the visualizer to break. It's not yet clear why this happens, the templated json appears to be correct.

**Comment by thermokarst** [comment]
This recently [came up on the forum](https://forum.qiime2.org/t/error-with-metadata-tabulate-in-qiime2-view/2538?u=thermokarst).

**Comment by thermokarst** [comment]
After spending some time looking at this, I think it might actually be the case that these failures were due to invalid JSON, not because the tables were too large.
